version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-guest}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST:-/}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbit_net

volumes:
  rabbitmq_data:

networks:
  rabbit_net:
